<?php
/**
 * @category    MineWhat
 * @package     MineWhat_Insights
 * @copyright   Copyright (c) MineWhat
 * @license     http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>
<?php $_product = $this->getProductToShoppingCart() ?>
<?php if ($_product && $_product["id"]) { ?>
<script type="text/javascript">
//<![CDATA[
	var _mwapi = _mwapi || [];
    	_mwapi.push(['trackEvent', 'addtocart', {pid: '<?php echo $_product["id"] ?>', sku: '<?php echo $_product["sku"] ?>', parent_pid: '<?php echo $_product["parentId"] ?>', qty: '<?php echo $_product["qty"] ?>', bundle: '<?php echo json_encode($_product["bundle"]) ?>'}]);
//]]>
</script>
<?php } ?>
